// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface ICreateTokenWithTokenMethodResponse {
    token: any;
}

export default class CreateTokenWithTokenMethodResponse {
    readonly _token: any;

    get token(): any {
        return this._token;
    }

    static tokenValidate(token: any): boolean {
        return;
    }

    constructor(props: ICreateTokenWithTokenMethodResponse) {
        this._token = props.token;
    }

    serialize(): ICreateTokenWithTokenMethodResponse {
        const data: ICreateTokenWithTokenMethodResponse = {
            token: this._token,
        };
        return data;
    }

    validate(): string[] {
        const validate = {};
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(
        props: Partial<ICreateTokenWithTokenMethodResponse>,
    ): CreateTokenWithTokenMethodResponse {
        return new CreateTokenWithTokenMethodResponse({
            ...this.serialize(),
            ...props,
        });
    }
}
