import PepProxy, {IPepProxy} from './PepProxy';

// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface ICreateAPepProxyResponse {
    pep_proxy: IPepProxy;
}

export default class CreateAPepProxyResponse {
    readonly _pep_proxy: PepProxy;

    get pepProxy(): PepProxy {
        return this._pep_proxy;
    }

    constructor(props: ICreateAPepProxyResponse) {
        this._pep_proxy = new PepProxy(props.pep_proxy);
    }

    serialize(): ICreateAPepProxyResponse {
        const data: ICreateAPepProxyResponse = {
            pep_proxy: this._pep_proxy.serialize(),
        };
        return data;
    }

    validate(): string[] {
        const validate = {
            pep_proxy: this._pep_proxy.validate().length === 0,
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<ICreateAPepProxyResponse>): CreateAPepProxyResponse {
        return new CreateAPepProxyResponse({...this.serialize(), ...props});
    }
}
