// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface ICreateRelationshipResponse {
    user_organization_assignments: any;
}

export default class CreateRelationshipResponse {
    readonly _user_organization_assignments: any;

    get userOrganizationAssignments(): any {
        return this._user_organization_assignments;
    }

    static userOrganizationAssignmentsValidate(
        userOrganizationAssignments: any,
    ): boolean {
        return;
    }

    constructor(props: ICreateRelationshipResponse) {
        this._user_organization_assignments =
            props.user_organization_assignments;
    }

    serialize(): ICreateRelationshipResponse {
        const data: ICreateRelationshipResponse = {
            user_organization_assignments: this._user_organization_assignments,
        };
        return data;
    }

    validate(): string[] {
        const validate = {};
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(
        props: Partial<ICreateRelationshipResponse>,
    ): CreateRelationshipResponse {
        return new CreateRelationshipResponse({...this.serialize(), ...props});
    }
}
