import IotAgent, {IIotAgent} from './IotAgent';

// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface ICreateAnIotAgentResponse {
    iot: IIotAgent;
}

export default class CreateAnIotAgentResponse {
    readonly _iot: IotAgent;

    get iot(): IotAgent {
        return this._iot;
    }

    constructor(props: ICreateAnIotAgentResponse) {
        this._iot = new IotAgent(props.iot);
    }

    serialize(): ICreateAnIotAgentResponse {
        const data: ICreateAnIotAgentResponse = {
            iot: this._iot.serialize(),
        };
        return data;
    }

    validate(): string[] {
        const validate = {
            iot: this._iot.validate().length === 0,
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(
        props: Partial<ICreateAnIotAgentResponse>,
    ): CreateAnIotAgentResponse {
        return new CreateAnIotAgentResponse({...this.serialize(), ...props});
    }
}
