import Role, {IRole} from './Role';

// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface ICreateARoleResponse {
    role: IRole;
}

export default class CreateARoleResponse {
    readonly _role: Role;

    get role(): Role {
        return this._role;
    }

    constructor(props: ICreateARoleResponse) {
        this._role = new Role(props.role);
    }

    serialize(): ICreateARoleResponse {
        const data: ICreateARoleResponse = {
            role: this._role.serialize(),
        };
        return data;
    }

    validate(): string[] {
        const validate = {
            role: this._role.validate().length === 0,
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(props: Partial<ICreateARoleResponse>): CreateARoleResponse {
        return new CreateARoleResponse({...this.serialize(), ...props});
    }
}
