// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IResetPasswordOfIotAgentResponse {
    new_password: string;
}

export default class ResetPasswordOfIotAgentResponse {
    readonly _new_password: string;

    get newPassword(): string {
        return this._new_password;
    }

    static newPasswordValidate(newPassword: string): boolean {
        return typeof newPassword === 'string' && !!newPassword.trim();
    }

    constructor(props: IResetPasswordOfIotAgentResponse) {
        this._new_password = props.new_password.trim();
    }

    serialize(): IResetPasswordOfIotAgentResponse {
        const data: IResetPasswordOfIotAgentResponse = {
            new_password: this._new_password,
        };
        return data;
    }

    validate(): string[] {
        const validate = {
            new_password:
                typeof this._new_password === 'string' && !this._new_password
                    ? true
                    : this._new_password,
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(
        props: Partial<IResetPasswordOfIotAgentResponse>,
    ): ResetPasswordOfIotAgentResponse {
        return new ResetPasswordOfIotAgentResponse({
            ...this.serialize(),
            ...props,
        });
    }
}
