import Permission, {IPermission} from './Permission';

// This file was autogenerated. Please do not change.
// All changes will be overwrited on commit.
export interface IUpdateAPermissionRequest {
    permission: IPermission;
}

export default class UpdateAPermissionRequest {
    readonly _permission: Permission;

    get permission(): Permission {
        return this._permission;
    }

    constructor(props: IUpdateAPermissionRequest) {
        this._permission = new Permission(props.permission);
    }

    serialize(): IUpdateAPermissionRequest {
        const data: IUpdateAPermissionRequest = {
            permission: this._permission.serialize(),
        };
        return data;
    }

    validate(): string[] {
        const validate = {
            permission: this._permission.validate().length === 0,
        };
        const isError: string[] = [];
        Object.keys(validate).forEach((key) => {
            if (!(validate as any)[key]) {
                isError.push(key);
            }
        });
        return isError;
    }

    update(
        props: Partial<IUpdateAPermissionRequest>,
    ): UpdateAPermissionRequest {
        return new UpdateAPermissionRequest({...this.serialize(), ...props});
    }
}
