// -*- mode: protobuf -*-
//
// A schema for Beancount's parser output. This is the intermediate state of the
// data, merely representing the production of the parser, before the subsequent
// processing (booking) that will produce the finalized directives.
//
// The data structures seen here are not visible in the final output nor to the
// regular plugins, which see the resolved ones produced after booking and
// interpolation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.8
// source: ledger/ledger.proto

package ledger

import (
	options "go.vixal.xyz/esp/ledger/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Container for all data produced by the parser, and the by Beancount in
// general (after booking, interpolation, and plugins processing.
type Ledger struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// A list of directives, with ownership.
	Directives []*Directive `protobuf:"bytes,1,rep,name=directives,proto3" json:"directives,omitempty"`
	// A list of errors encountered during parsing and processing.
	Errors []*Error `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty"`
	// Parsed options.
	Options *options.Options `protobuf:"bytes,3,opt,name=options,proto3,oneof" json:"options,omitempty"`
	// Processing details.
	Info *options.ProcessingInfo `protobuf:"bytes,4,opt,name=info,proto3,oneof" json:"info,omitempty"`
}

func (x *Ledger) Reset() {
	*x = Ledger{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ledger_ledger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Ledger) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ledger) ProtoMessage() {}

func (x *Ledger) ProtoReflect() protoreflect.Message {
	mi := &file_ledger_ledger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ledger.ProtoReflect.Descriptor instead.
func (*Ledger) Descriptor() ([]byte, []int) {
	return file_ledger_ledger_proto_rawDescGZIP(), []int{0}
}

func (x *Ledger) GetDirectives() []*Directive {
	if x != nil {
		return x.Directives
	}
	return nil
}

func (x *Ledger) GetErrors() []*Error {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *Ledger) GetOptions() *options.Options {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *Ledger) GetInfo() *options.ProcessingInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

var File_ledger_ledger_proto protoreflect.FileDescriptor

var file_ledger_ledger_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x1a, 0x11, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x1a, 0x1c, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xda,
	0x01, 0x0a, 0x06, 0x4c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x0a, 0x64, 0x69, 0x72,
	0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65,
	0x52, 0x0a, 0x64, 0x69, 0x72, 0x65, 0x63, 0x74, 0x69, 0x76, 0x65, 0x73, 0x12, 0x25, 0x0a, 0x06,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x06, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x73, 0x12, 0x2f, 0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x48, 0x00, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x73, 0x88, 0x01, 0x01, 0x12, 0x30, 0x0a, 0x04, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x69, 0x6e, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x48, 0x01, 0x52, 0x04, 0x69,
	0x6e, 0x66, 0x6f, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x6f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x42, 0x19, 0x5a, 0x17, 0x67,
	0x6f, 0x2e, 0x76, 0x69, 0x78, 0x61, 0x6c, 0x2e, 0x78, 0x79, 0x7a, 0x2f, 0x65, 0x73, 0x70, 0x2f,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ledger_ledger_proto_rawDescOnce sync.Once
	file_ledger_ledger_proto_rawDescData = file_ledger_ledger_proto_rawDesc
)

func file_ledger_ledger_proto_rawDescGZIP() []byte {
	file_ledger_ledger_proto_rawDescOnce.Do(func() {
		file_ledger_ledger_proto_rawDescData = protoimpl.X.CompressGZIP(file_ledger_ledger_proto_rawDescData)
	})
	return file_ledger_ledger_proto_rawDescData
}

var file_ledger_ledger_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ledger_ledger_proto_goTypes = []interface{}{
	(*Ledger)(nil),                 // 0: ledger.Ledger
	(*Directive)(nil),              // 1: ledger.Directive
	(*Error)(nil),                  // 2: ledger.Error
	(*options.Options)(nil),        // 3: options.Options
	(*options.ProcessingInfo)(nil), // 4: options.ProcessingInfo
}
var file_ledger_ledger_proto_depIdxs = []int32{
	1, // 0: ledger.Ledger.directives:type_name -> ledger.Directive
	2, // 1: ledger.Ledger.errors:type_name -> ledger.Error
	3, // 2: ledger.Ledger.options:type_name -> options.Options
	4, // 3: ledger.Ledger.info:type_name -> options.ProcessingInfo
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_ledger_ledger_proto_init() }
func file_ledger_ledger_proto_init() {
	if File_ledger_ledger_proto != nil {
		return
	}
	file_ledger_data_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_ledger_ledger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Ledger); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_ledger_ledger_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ledger_ledger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ledger_ledger_proto_goTypes,
		DependencyIndexes: file_ledger_ledger_proto_depIdxs,
		MessageInfos:      file_ledger_ledger_proto_msgTypes,
	}.Build()
	File_ledger_ledger_proto = out.File
	file_ledger_ledger_proto_rawDesc = nil
	file_ledger_ledger_proto_goTypes = nil
	file_ledger_ledger_proto_depIdxs = nil
}
